### ISSUE TITLE
[BUG] Some playbook links lead to the rendered docs, others to the repo

### ISSUE THREAD

**Issue by day-jeff** [microsoft/code-with-engineering-playbook#1008]
Transferring this bug report from an internal playbook repo:

@cdw commented on Oct 6, 2022
It would be nice to choose between:

https://github.com/microsoft/code-with-engineering-playbook
https://microsoft.github.io/code-with-engineering-playbook/
As the base URL

**Comment by TessFerrandez** [comment]
fixed
