### ISSUE TITLE
Guidance on how to include the right SMEs

### ISSUE THREAD

**Issue by debugerr** [microsoft/code-with-engineering-playbook#107]
Guidance on rules who to include and how do you find the right people to look at your changes.

**Comment by TessFerrandez** [comment]
I have been looking at potentially picking up this issue a few times now, but not sure what it entails or if it is needed. Is this something that we need to give guidance on? and is it something where best practices that are not just common sense exists?

**Comment by TessFerrandez** [comment]
Closing per discussion on teams
