### ISSUE TITLE
Verify Code Review Recipe for C#

### ISSUE THREAD

**Issue by debugerr** [microsoft/code-with-engineering-playbook#113]
Validate the content for the specific language and make sure it is up to date. 

Use the following template to structure the content:

1. linters / code formatters
2. enforcement in build pipelines
3. Starter Code Review Checklist
4. tools/extensions/plugins for VS Code and VS
5. Language specifics

**Comment by TessFerrandez** [comment]
Adding an MD template that can be used for all languages
https://github.com/microsoft/code-with-engineering-playbook/blob/master/pull-requests/code-reviews/recipes/CSharp.md

# <language> Code Reviews
## Style Guide 
Link to the official style guide

## Linters
A selection of suggested linters

## Useful extensions for VS Code and Visual Studio
Ex. configuration of linters, or similar

## Sample Build Validation Pipeline
Ex. yaml pipeline that runs a linter and/or tests as applicable

## Code Review Checklist
In addition to the Code Review checklist, you should also look for these additional TypeScript related code review items:
...

## Language specific sections
