### ISSUE TITLE
Create a Code Review Recipe for Java

### ISSUE THREAD

**Issue by debugerr** [microsoft/code-with-engineering-playbook#115]
Guidance on how to CR the language and what tools can be used in the process to support the CR process

**Comment by TessFerrandez** [comment]
Create the recipe https://github.com/microsoft/code-with-engineering-playbook/blob/master/pull-requests/code-reviews/recipes/Java.md with the relevant sections from below

# <language> Code Reviews
## Style Guide 
Link to the official style guide

## Linters
A selection of suggested linters

## Useful extensions for VS Code and Visual Studio
Ex. configuration of linters, or similar

## Sample Build Validation Pipeline
Ex. yaml pipeline that runs a linter and/or tests as applicable

## Code Review Checklist
In addition to the Code Review checklist, you should also look for these additional TypeScript related code review items:
...

## Language specific sections
