### ISSUE TITLE
Recommended practice and guidelines

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/code-with-engineering-playbook#125]
1. Review existing recommended practice sections
2. Identify guidelines that can be added

**Comment by katyamust** [comment]
Recommended Tools and Approaches and Tools section are missing in the main read.me

**Comment by katyamust** [comment]
Logs vs Metrics and ml observability articles are not referenced. in main read.me section.

**Comment by katyamust** [comment]
I think recommended practices and pitfalls to avoid can be combined in one section.

**Comment by katyamust** [comment]
Reviewed and created new issue on about points. Closing this one.
