### ISSUE TITLE
Design the top-level table of contents / topics for source code playbook section

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/code-with-engineering-playbook#138]
Determine what sections we should have
How they should be organized
Update the table of contents
https://github.com/microsoft/code-with-engineering-playbook/tree/master/source-control

**Comment by rozele** [comment]
- [x] Contributing Guidelines
  - [x] Commit best practices (move from main README)
  - [x] Contributing to an existing repository
  - [x] Creating a new repository
  - [x] Merge strategies (previously: Commit history)
  - [x] Branch naming
- [ ] Feature branching
- [x] Release and versioning
- [x] Working with secrets (move from git.md)
- [ ] Git Guidance
  - [ ] The Basics
    - [ ] Cloning
    - [ ] Committing
    - [ ] Merging
    - [ ] Managing Remotes
  - [ ] Rolling back changes
    - [x] Reverting and deleting commits
    - [ ] Using the reflog
  - [x] Using submodules (previously: Multi service development and deployments)
  - [x] Stashing changes (previously: Stashing)
  - [x] Working with large files (previously: Working with images, video …)
  - [ ] Git tools and resources

**Comment by suroor-fatima** [comment]
Do we need to add GitOps ? Is this covered else where?
