### ISSUE TITLE
Update branch naming guidance

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/code-with-engineering-playbook#139]
https://github.com/microsoft/code-with-engineering-playbook/blob/master/source-control/git.md
 
As an example:
For our projects we have generally used feature/<taskid>-task_description or bug/<taskid>_bug_description which I thought was the gitflow way of naming branches --- 

Current section

Naming branches
Let's use the following naming conventions for branches:

	personal branches: user/your_alias/feature_name
	feature branches for staging (testing, integration,...): staging/feature_name
	release branches: release/release_name

**Comment by rozele** [comment]
I think this depends on the environment (GitHub vs. AzDO vs. etc.) you're working in and the project you are working on. Our first and foremost guidance should be "Review the contributing guidelines for the project you are working on."

We shouldn't get too prescriptive here, I've seen everything from the ones you've posted and also things like:
```
alias/issue(\d+)
alias/bug(\d+)
...
```

Depending on how your team manages release branches, you may have just "1.0-stable", "1.1-stable", etc. for release branches. I don't think this playbook should postulate that there is a correct way to name branches.

**Comment by TessFerrandez** [comment]
@rozele I agree, that is the reason I wanted to update this section... to say that the naming convention should be agreed upon, and also to link to gitflow as a default suggestion if none is given, rather than the suggestions in the section I pointed out.  (For clarification, the list above is what is in the document now).

**Comment by TessFerrandez** [comment]
Make this section less prescriptive and perhaps suggest the git flow conversion as a base
