### ISSUE TITLE
Add section on Git Tools

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/code-with-engineering-playbook#141]
- Git usage in VS Code or VS
- Links to other good tools like Git Extensions, Fork, Kdiff3 etc.

**Comment by rozele** [comment]
I think our stance should be "we're not opinionated on how you manage git, so long as you abide by the branching policies / commit message best practices / etc." and we can link to:
- https://git-scm.com/downloads/guis
- https://code.visualstudio.com/docs/editor/versioncontrol

**Comment by TessFerrandez** [comment]
The git.md already links to these so I am closing this issue
