### ISSUE TITLE
Add guidance on secrets in source code

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/code-with-engineering-playbook#142]
There is an overlap here with a few different sections so check the other sections to make sure we keep the docs DRY

- guidance on handling secrets .gitignore
- handling template files to understand how .env files or local.settings.json etc. should be filled out

**Comment by rozele** [comment]
There's also already a recipe in the playbook about encrypting your .env / secrets file for local dev:
https://github.com/microsoft/code-with-engineering-playbook/blob/78599ff79d3c5b2ab9dc0227164e1a16093f469a/continuous-deployment/secrets-management/recipes/azure-devops/secrets-per-branch.md

**Comment by rozele** [comment]
And we may want to check with @anthturner if there are plans to contribute git hooks or tools around DevSecOps that we should link to.
