### ISSUE TITLE
Suggestion: Terraform best practices.

### ISSUE THREAD

**Issue by tobecodex** [microsoft/code-with-engineering-playbook#15]
Proposing we have a section relating to best practices wrt Terraform.

**Comment by seushermsft** [comment]
@charleszipp - Details about your terraform VSO task seem like great content for starting the terraform best practices page.

**Comment by charleszipp** [comment]
@seushermsft i would be willing to help get this page going with the azure devops pipelines task. Feel free to assign to me.

**Comment by lawrencegripper** [comment]
I've written this up as a blog based on the work in a current sprint. 

Content is here, let me know if you'd like me to PR into the repo.

https://blog.gripdev.xyz/2019/07/16/friends-dont-let-friends-commit-terraform-without-fmt-linting-and-validation/
