### ISSUE TITLE
Suggest specific git branch naming convention for this repo

### ISSUE THREAD

**Issue by MS-Santi** [microsoft/code-with-engineering-playbook#155]
As this repo holds our engineering practices guidance, we should follow it while maintaining this repo.
There is general guidance provided, but not a specific one for this project.
At the time of opening this issue, current names are:

- master
- feature/111-update-python-source-code-guidance
- feature/151-standardize-cr-recipes
- limorl-contrib
- obs/cor-id
- refactor-fenocera
- revert-9-master
- test_branch

**Comment by TessFerrandez** [comment]
Completely agree :)

**Comment by rozele** [comment]
See comments in PR - I don't think we need to worry about branch naming. The actions we should take are:
1. Delete all branches in this repo that are not `master`
2. Disable all push permissions for anyone on this repo (other than whoever the owner may be)
3. Add guidance that all people contribute PRs through forks of this repo
