### ISSUE TITLE
Discuss merging strategy for this repo

### ISSUE THREAD

**Issue by MS-Santi** [microsoft/code-with-engineering-playbook#158]
The contributing.md document (Merging Strategy section) states that non-linear merges are the preferred strategy. However, this hasn't been explicitly discussed.
Discuss the merging strategy and either:
- select another merging strategy and document it. Close the issue.
or
-  accept the documented section as is. Close the issue.

**Comment by rozele** [comment]
@MS-Santi I don't see anything in the Contributing.md section.

I do see that the merging strategy for this repo is already configured to disable merge commits (and our default is squash and merge).

Seems that the merging strategy has already been defined, so I'm going to close this.
