### ISSUE TITLE
AppInsights-on-premises

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/code-with-engineering-playbook#162]
Add to possibly Tools and Recommendations?

AppInsights-on-premises. From past experience, issues related to telemetry can be hard to catch since often people don't unit-test for this and it’s non-trivial to use an AppInsights resource for testing (e.g. managing the lifetime of the resource, having to ignore old telemetry for assertions, if a new resource is used it can take a while for the telemetry to show up, etc.). The CSE NYC team built AppInsights-on-premises to make it easier to integrate with an AppInsights endpoint during local development or CI without having to spin up a resource in Azure.
 
Besides being able to assert without Azure connectivity that the application is indeed sending telemetry, another nice aspect is that we can use assertions on the stored telemetry (e.g. events or exceptions) for end to end tests. E.g. on one of my projects we have a heavily async workflow including a web tier and background workers and we're using assertions on the AppInsights telemetry stored locally to check if the workers did indeed do the correct processing and didn't throw any exceptions.

**Comment by ivaramme** [comment]
I love it @NarmathaBala - I was taking with my team about suggesting this project you mentioned to one of our customers that mostly using integration tests in their projects. Let me know how it goes in your project later on.

**Comment by NarmathaBala** [comment]
> I love it @NarmathaBala - I was taking with my team about suggesting this project you mentioned to one of our customers that mostly using integration tests in their projects. Let me know how it goes in your project later on.

@ivaramme  - This was an initiative from @c-w . He is currently out on paternity leave and will be back end of March. Github repo https://github.com/c-w/appinsights-on-premises
