### ISSUE TITLE
Tech Lead check list should be distributed to each EF team

### ISSUE THREAD

**Issue by MS-Santi** [microsoft/code-with-engineering-playbook#176]
The file TECH-LEADS-CHECKLIST.md is currently a static list of items.
To ensure that each EF working group is in charge of its share of the check list for tech leads, there should be one file in each EF folder for that particular check list and a page in the root folder that links to each.

**Comment by TessFerrandez** [comment]
I don't agree with this.  For the reader (Tech Lead) it is better if we have one common list.  
Each working group can still manage the sections separately.

**Comment by TessFerrandez** [comment]
@fnocera comments on this?

**Comment by TessFerrandez** [comment]
Each EF team seems to be updating their part of this individually so closing this issue
