### ISSUE TITLE
Guidance on structure and management of multiple repositories

### ISSUE THREAD

**Issue by tompaana** [microsoft/code-with-engineering-playbook#193]
Most of the CSE projects will have multiple repositories, especially engagements around microservices.

* How to make sure PRs get handled in time and won't turn stale?
* Where to place common documentation (obviously each repo should have its own README the very least)?
* Propagating branch policies, pipelines etc. over several repos (link to CRs README where appropriate)
* How to build dashboards (or using other tools) to aggregate relevant information from several repos?
* Guidelines on when to move content into separate repositories - what are the indicators?

**Comment by katyamust** [comment]
@tomipaa Do you have an ideas on how approach this issue? Should we split it in to different issues?

**Comment by tompaana** [comment]
@katyamust I'll preserve some time next week to go over the topic. As you said, not all of the bullet points make even sense to be covered in the playbook.

**Comment by katyamust** [comment]
@tomipaa Thank you, Tomi!

**Comment by tompaana** [comment]
I feel this issue is redundant; the normal guidance/best practices that apply in normal situations (one or two repositories) can scale. And if it doesn't scale, then it must be some special scenario for which there are no silver bullets. Special solution -> blog post rather than flimsy guidelines.

I suggest to close this issue.

**Comment by katyamust** [comment]
Closed as agreed in the sync meeting.
