### ISSUE TITLE
Tools and guides - Promethesus (Metrics)

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/code-with-engineering-playbook#222]
Recommended tools section is currently very web/Azure/App Insights focussed.

With the purpose of providing insight into tools and their purposes, best practices, starter templates/recipes (if available)

1. Contribute content for Promethesus - Purpose and usage application scenarios
2. Recommended approaches
3. What to watch for
4. Recipes / Starter templates

**Comment by lakshaykaushik** [comment]
Hi @NarmathaBala , can i pick this up and raise a PR?

**Comment by TessFerrandez** [comment]
@narmathabala and @lakshaykaushik - this has been stale for a while, is this still an active issue?
