### ISSUE TITLE
Tooling and guides: Loki (Logging)

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/code-with-engineering-playbook#225]
https://github.com/grafana/loki
Recommended tools section is currently very web/Azure/App Insights focussed.

With the purpose of providing insight into tools and their purposes, best practices, starter templates/recipes (if available)

Contribute content for Loki - 
1. Purpose and usage application scenarios
2. Recommended approaches
3. What to watch for
4. Recipes / Starter templates

**Comment by Guilhermeslucas** [comment]
Happy to jump on this one! Can I?

**Comment by katyamust** [comment]
Absolutely! Thank you @Guilhermeslucas !
