### ISSUE TITLE
Developer Blog link is broken

### ISSUE THREAD

**Issue by allantargino** [microsoft/code-with-engineering-playbook#243]
On CSE page, there is a link on the bottom pointing to Microsoft developer blog, but it's broken:
https://github.com/microsoft/code-with-engineering-playbook/blob/master/CSE.md

**Comment by brijrajsingh** [comment]
I think its not broken any more, its landing here https://devblogs.microsoft.com/cse/

**Comment by TessFerrandez** [comment]
I confirm that it is not broken

**Comment by allantargino** [comment]
Thanks, it's not broken anymore 👍
