### ISSUE TITLE
Restructure the readme

### ISSUE THREAD

**Issue by debugerr** [microsoft/code-with-engineering-playbook#254]
Currently we have a pretty large readme page that contains a lot of information. I would like to try to restructure it into smaller subsections and have a more condensed readme that provides the most important information.

**Comment by TessFerrandez** [comment]
@debugerr Can you at the same time do a few other things

- The goals are equally important so they should be an unordered list
- Other sections also contain unneccessarily ordered lists with sublist items making it hard to read.  An option would be to use subtitles instead for the list items so we only have one level of indentation for the items (i.e. **Understanding the code you are reviewing** would be a subtitle) - this applies to all sections except for Evidence and Measures that is already structured pretty nicely

**Comment by TessFerrandez** [comment]
Keep in mind also that many other documents point to sections in the code review document, just a reminder so you update those as well. E.g. the tech lead list, sprint structure etc.

**Comment by ChrisRisner** [comment]
In looking at the Readme, it might make sense to split out separate pages for the primary scenarios.  I'm thinking potentially a page for PR Author Guidance, one for PR Reviewer Guidance, one for Design & Code Quality (this is kind of guidance for both), and one for Evidence and Measures.
