### ISSUE TITLE
Update the working agreement

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/code-with-engineering-playbook#269]
The working agreement document is incomplete.
Rewrite this document, fill out the existing sections and add new relevant sections

https://github.com/microsoft/code-with-engineering-playbook/blob/master/team-agreements/working-agreements/readme.md

**Comment by niksacdev** [comment]
@TessFerrandez - we have a working agreement created internally in cwcwiki, do we need a public version as well?

**Comment by TessFerrandez** [comment]
The working agreement already exists in the playbook, it is just not fleshed out.

@niksacdev I think it is good to keep the work agreement in the playbook as it is something we share with our customer team, and it's applicable to non CSE projects as well.  Is there a reason you feel it should not be there?  

If there are more internal parts of it we could place them/keep them in the wiki, but I can't find a reason this should be internal only so would be interested in hearing your thoughts.
