### ISSUE TITLE
Add info about interactive rebase for undoing commits

### ISSUE THREAD

**Issue by rozele** [microsoft/code-with-engineering-playbook#272]
Add information to `./source-control/git-guidance/readme.md#reverting-and-deleting-commits` about interactive rebase.

**Comment by lakshaykaushik** [comment]
Hi @annazietlow , can i pick this up and raise a PR?

**Comment by lakshaykaushik** [comment]
Created a Pull request https://github.com/microsoft/code-with-engineering-playbook/pull/501 which will close this issue. Request for review
