### ISSUE TITLE
Add information about VS Code as a git GUI to source-control section

### ISSUE THREAD

**Issue by rozele** [microsoft/code-with-engineering-playbook#274]
We have a section on git tools that is missing one of the most popular, VS Code. Should mention how it's useful for staging changes and reviewing diffs. Add to `./source-control/git-guidance/readme.md#tools`

Really we may just want to add a link to key sections from this document:
https://code.visualstudio.com/docs/editor/versioncontrol#_git-support

**Comment by fnocera** [comment]
@sapinderpalsingh expressed interest in this issue. He needs to join the Microsoft org on github then I can add him as a contributor, just FYI @rozele @TessFerrandez
