### ISSUE TITLE
Add reference for unit testing node JS using Mocha

### ISSUE THREAD

**Issue by munishm** [microsoft/code-with-engineering-playbook#284]
We should add some references for unit testing Node JS (https://github.com/microsoft/code-with-engineering-playbook/blob/master/test-first-development/unit-testing/readme.md) , the current official documentation is in Jest and CSE engineering playbook prefers Mocha over Jest so I think we should add some starters/examples for it

**Comment by TessFerrandez** [comment]
Closing issue as PR is closed
