### ISSUE TITLE
Minimalism should be removed

### ISSUE THREAD

**Issue by emrekenci** [microsoft/code-with-engineering-playbook#32]
**https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalismRules.md**

It seems this manifesto popped up in hackernews a few months ago and hasn't even got much attention. Rightfully so because these are not widely accepted principles like the agile manifesto. And therefore doesn't belong in a Microsoft engineering playbook.

In fact, some items in this are gibberish IMO.

- Perfect is enemy of good, first do it, then do it right, then do it better
- Basics, first. Follow always a top-down thinking starting by the best-practices of CS.
- Think different. Simple is harder than complex, which means you'll need to use your creativity.

While some other items are a no-brainer or things that can be inferred from existing agile practices.

If we want to add a manifesto into the playbook, let's add the agile manifesto.

**Comment by emrekenci** [comment]
@max-mironov @cloudbeatsch

**Comment by max-mironov** [comment]
Hey @emrekenci, thanks so much for feedback! 
Agreed that some items from this manifesto are discussable;) 
I could eagerly create a PR and replace it with [Agile Manifesto](https://agilemanifesto.org/iso/en/principles.html) principles. 
Please let me know if sounds good for you.

**Comment by emrekenci** [comment]
Sorry I missed this, @max-mironov. Yes, please do that.

Discussible to say the least :)

**Comment by max-mironov** [comment]
@emrekenci Please take a look at PR https://github.com/Microsoft/code-with-engineering-playbook/pull/34. 
We can discuss it and modify accordingly if needed.
