### ISSUE TITLE
Observability Readme.me update

### ISSUE THREAD

**Issue by katyamust** [microsoft/code-with-engineering-playbook#330]
1. Recommended Tools and Approaches and Tools section are missing in the main read.me

2. Logs vs Metrics and ml observability articles are not referenced. in main read.me section.

3. Consolidate content of "Recommended practices" and "Pitfalls to avoid" in one section.

**Comment by NarmathaBala** [comment]
Added links to ml observability
consolidated content for recommended practices and pitfalls into one section
Fixed other missing sections
