### ISSUE TITLE
Move security checklist into TL checklist

### ISSUE THREAD

**Issue by anthturner** [microsoft/code-with-engineering-playbook#339]
We have content elsewhere for a security-focused appdev checklist for tech leads. That needs to be merged into the TL checklist here... https://github.com/microsoft/code-with-engineering-playbook/blob/master/TECH-LEADS-CHECKLIST.md#security---to-do

**Comment by TessFerrandez** [comment]
@anthturner - this issue has been stale for some time, is this issue still active or ok to close

**Comment by anthturner** [comment]
@TessFerrandez As I'm no longer with Microsoft, I leave this up to you and/or the current security teams to make a call on. 🙂
