### ISSUE TITLE
Definition of done and ready: check consistency with CSE recent guidelines

### ISSUE THREAD

**Issue by meulta** [microsoft/code-with-engineering-playbook#343]
- https://github.com/microsoft/code-with-engineering-playbook/tree/master/team-agreements/definition-of-done
- https://github.com/microsoft/code-with-engineering-playbook/tree/master/team-agreements/definition-of-ready

**Comment by TessFerrandez** [comment]
@meulta Can you point to the recent guidelines?

**Comment by meulta** [comment]
I think that just making sure it is in sync with https://cwcwiki.com/wiki/Definition_of_Done (internal link) would be great.

**Comment by TessFerrandez** [comment]
@meulta should we close this issue - or how do you feel about the above?

**Comment by meulta** [comment]
Yes we can close this!
