### ISSUE TITLE
Document How to Gain Access to a Customer's Azure DevOps

### ISSUE THREAD

**Issue by Smarker** [microsoft/code-with-engineering-playbook#36]
Oftentimes a customers use Azure DevOps, but do not have AAD set up correctly.

Without AAD set up, it is impossible to grant permissions to `@microsoft.com` addresses. Since setting up AAD is not always intuitive for the customer, people often suggest to use a non-Microsoft `MSA` account. Then the customer would end up granting project access to `@hotmail.com` or `@outlook.com` addresses, which isn't something CELA would support.

The steps to properly set up VSTS with `@microsoft` accounts as members would help us "do the right thing" when collaborating with customers and help us get to the "coding with" quicker.

**Comment by TessFerrandez** [comment]
This is more an issue for internal wiki - doesn't seem to fit for the playbook
Closing
