### ISSUE TITLE
Remove devcontainers from this repo

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/code-with-engineering-playbook#360]
This repo should be seen as more of a book than a code repo - and while small snippets of sample code is appropriate in running text we want to avoid having large chunks of code in the repo that we have to maintain, check for security issues etc. etc.

In addition, placing code in this repository makes it not very discoverable.  A more appropriate location for the dev containers would be the [VS Code Dev Containers Repo](https://github.com/microsoft/vscode-dev-containers/tree/master/containers)

This issue should be focussed around: 
1) Removing the .devcontainer (https://github.com/microsoft/code-with-engineering-playbook/tree/master/continuous-integration/devcontainers/terraform/.devcontainer)
2) Adding a page/section in the developer experience section that introduces the high level concept/need of dev containers and provides a link to the VSCCode dev containers repo, as well as direct links to a few commonly used containers if we have recommendations. 
3) Linking from CI section to the new page on dev containers in the developer experience section

Adding @fnocera and @charleszipp as we have discussed this in recent PRs and @JasonTheDeveloper and @erikschlegel as you have contributed the code for the containers

---------
The above issue was edited by @fnocera on 09/09

**Comment by TessFerrandez** [comment]
More specifically this applies to https://github.com/microsoft/code-with-engineering-playbook/tree/master/continuous-integration/devcontainers/terraform/.devcontainer

**Comment by erikschlegel** [comment]
@TessFerrandez  - Let's discuss during the next champions sync to make sure we're all on the same page with the intent of the playbook repo. I don't agree with the above statement: 
> placing code in this repository makes it not very discoverable.

**Comment by charleszipp** [comment]
> @TessFerrandez - Let's discuss during the next champions sync to make sure we're all on the same page with the intent of the playbook repo. I don't agree with the above statement:
> 
> > placing code in this repository makes it not very discoverable.

I believe @TessFerrandez's intent in suggesting this is that the dev container samples would be _more_ discoverable if they were contributed to an existing, established, and managed repo whose purpose is solely committed to sharing dev container samples. There is an `azure-terraform` dev container within the repo @TessFerrandez pointed out. Perhaps that could be updated to include the language server?

**Comment by charleszipp** [comment]
I would also add that i recently tried using the terraform dev container from that repo and didnt have the best of luck. It seems to be adding quite a bit of extra software into the container. Its not clear why most of it is needed. So I ended up creating my own that just adds azure cli, terraform, and tflint. 

I say that to suggest I think there is opportunity to improve the sample for terraform within that repo.

**Comment by fnocera** [comment]
I have edited the issue to add the specifics of what should be covered: not only removing the devcontainer sample from this repo but adding a page on devcontainers that links to the VSCode containers repo and provides links to some commonly used containers. 

Thoughts? @charleszipp @TessFerrandez @erikschlegel

**Comment by charleszipp** [comment]
LGTM @fnocera
