### ISSUE TITLE
Adding guidance on documentation

### ISSUE THREAD

**Issue by lawrencegripper** [microsoft/code-with-engineering-playbook#373]
Hi, 

I wanted to add a section on basics of documentation and more specifically how to automate some simple checks. 

![image](https://user-images.githubusercontent.com/1939288/91285333-00e69700-e785-11ea-9d6d-910164533327.png)

- https://github.com/tcort/markdown-link-check
- https://github.com/tmaier/docker-markdown-spellcheck
- Markdown linting too maybe (arguable I don't care as much about that)

Is this a good addition and where should it live?

**Comment by TessFerrandez** [comment]
@lawrencegripper looks like a good addition
Best location would be https://github.com/microsoft/code-with-engineering-playbook/blob/master/code-reviews/recipes/Markdown.md where we already have documentation around linting, good English etc.

**Comment by TessFerrandez** [comment]
@lawrencegripper will you be adding this yourself or do you want to leave it open for someone else to take the issue? - if you take it yourself, can you self assign so others know it is taken care of

**Comment by lawrencegripper** [comment]
Hey, sorry @TessFerrandez been swamped on project spin-up. 

Hoping to pick this up as things get calmer my end. I'll leave it unassigned now and if someone gets to it before me that's fine by me or I'll assign when I start working on it. Sound like a good plan?

**Comment by brockneedscoffee** [comment]
@lawrencegripper @TessFerrandez I came here to look to see if there was anything around this (we just automated this in our project) mind if I take a shot at it?

**Comment by TessFerrandez** [comment]
Go for it! If you want you can set me and @lawrencegripper as reviewers when done.

**Comment by brockneedscoffee** [comment]
I don't seem to have the ability to write to the repo to create a branch for a PR.  Can you help with that @TessFerrandez

**Comment by TessFerrandez** [comment]
You should be able to fork the repo, then PR from the fork. Then I can merge when the PR is ready. This is the recommended way for occasional contributors.

If you plan to contribute a lot, check with @fnocera - you need to be a member of the MS github org first

**Comment by brockneedscoffee** [comment]
I plan to contribute a lot, I am part of CSE Gov.  I just requested to join the code-with collaborators group in the mean time I will fork it.  Thanks!

**Comment by magencio** [comment]
I'm working on a complete new Playbook section focused 100% on Documentation. I'm currently gathering all the efforts to add guidance on documentation, including automation, with the idea of adding them under this new section. @brockneedscoffee, what is the status of your work on this? Thank you.

**Comment by magencio** [comment]
We already added basic content related to this here https://github.com/microsoft/code-with-engineering-playbook/blob/main/docs/documentation/tools/automation.md. Thus I'm closing this issue.
