### ISSUE TITLE
Add pairing/swarming best practices

### ISSUE THREAD

**Issue by AdanOrtiz** [microsoft/code-with-engineering-playbook#384]
Adapt the existing documentation that came out of recent customer engagement to add pairing/swarming best practices to playbook under agile-development/collaboration

**Comment by codepossible** [comment]
We have using a similar concept in the past few projects. We call it "mobbing" and the participants "mobsters", just add some flair to it. (Pin stripe suit, optional). We using the concept to explore areas which "mobsters" may be new to or as mechanism to unblock another teammate/mobster. I will reach out to you on Microsoft Teams to learn more about how you have use the "swarm".

It is a step above from pairing. As I might point out - "two is a pair, three is a mob, four is tribe, more than that is a crowd"...  :)
