### ISSUE TITLE
Add concepts learnings for enabling execution of pipeline activities locally

### ISSUE THREAD

**Issue by charleszipp** [microsoft/code-with-engineering-playbook#426]
Having the ability to execute pipeline activities locally has been identified as an opportunity to promote positive developer experience. There have been some patterns identified for how to best to achieve this in several engagements.

This issue will add a document to the developer experience section that describes common practices and patterns for enabling execution of pipeline activities from a developer workstation. These include but, not limited to:

1. Build
2. Lint
3. Unit test
4. E2E test
5. Deploy

**Comment by liliankasem** [comment]
I can pick this up :)

**Comment by charleszipp** [comment]
> I can pick this up :)
> 
> Q: Is this referring to running something like the AzDO pipelines locally - is that even possible? Or more like running those steps individually or part of some local script or pre-commit hook?

@liliankasem apologies for the delayed response. I think this came in while I was OOO. 

This was referring to implementing these activities in a way that they can be run both locally and from a pipeline. One (probably oversimplified) example would be scripting out these activities in shell then having the AzDO pipeline simply execute the shell commands. I have seen this approach in a couple projects. Toby Bradshaw had recommended this and probably has more examples and guidance he can share.

**Comment by charleszipp** [comment]
AFAIK, azure pipelines yaml cannot be executed/tested locally. That would be an awesome feature though if it did!

**Comment by charleszipp** [comment]
@liliankasem as a heads up im experimenting with how to do this using my terraform task extension. I have gotten some info from devops SA that might open up some possibilities here. However, think it would still be useful to document approaches i mentioned in earlier comment in case this doesnt prove out.

**Comment by liliankasem** [comment]
Nice! Sorry I haven't found the time to do much here, if you want to take this over I'm more than okay with that. If you're also super busy, you can add your findings to the document after I get the initial PR in :)

**Comment by charleszipp** [comment]
@itye-msft has volunteered to provide some examples of how they have been tackling this.
