### ISSUE TITLE
Add recipe for remote debugging with bridge to kubernetes and the UI dashboard

### ISSUE THREAD

**Issue by charleszipp** [microsoft/code-with-engineering-playbook#428]
Not all solutions can be run locally. This can be due to using a cloud service that does not offer a local emulator or a local runtime environment. In these cases it may be necessary to deploy a service into a cloud environment to perform end-to-end testing. When this end-to-end testing is being done it can be very useful to be able to attach a debugger (as one would if the entire solution could be run locally).

This issue will create a article describing an approach for enabling remote debugging using the Bridge to Kubernetes tool and UI Dashboard.

**Comment by norelina** [comment]
I would love to work on this one - @tasdevani21 let me know if you want to collaborate? :)

**Comment by norelina** [comment]
@charleszipp @tasdevani21 per our discussion I think we can close this issue as will try to contribute directly to https://code.visualstudio.com/docs/containers/bridge-to-kubernetes, and we will look into Observability section possibly being a better home for the K8s dashboard.

**Comment by charleszipp** [comment]
Closing as we found a home for the content that will be more widely available to the public
