### ISSUE TITLE
add scenarios for observability as code

### ISSUE THREAD

**Issue by Guilhermeslucas** [microsoft/code-with-engineering-playbook#457]
After taking a look at this [pr](https://github.com/microsoft/code-with-engineering-playbook/pull/376#event-4175338877) and talking to @NarmathaBala, it came to my mind that we can list some scenarios for observability as code. For example: we can talk about alert creation automation, dashboard definition as code, etc.

**Comment by lakshaykaushik** [comment]
Hi @Guilhermeslucas , can i pick this up and raise a PR?

**Comment by Guilhermeslucas** [comment]
Yes! Thanks :)
