### ISSUE TITLE
Add contents on BDD in automated-testing/unit-testing

### ISSUE THREAD

**Issue by akirakakar** [microsoft/code-with-engineering-playbook#459]
Adding contents around BDD with "Given, When, Then"(GWT) format in addition to TDD with AAA format.

Ref: 
https://github.com/microsoft/code-with-engineering-playbook/tree/master/automated-testing/unit-testing#test-driven-development

**Comment by TessFerrandez** [comment]
@akirakakar if you plan on working on the issue, please assign it to yourself, or if you don't have permissions, comment on the issue, so we know it is being worked on

**Comment by akirakakar** [comment]
@TessFerrandez I haven't started to work on yet and don't want to block anybody to pick this up if they want.
I will ask you to assign me (as I don't seem to have permission to do so) if I start working on it before somebody picks up.

**Comment by TessFerrandez** [comment]
@akirakakar - this issue has been stale for some time, I will go ahead and close and you can reopen later if you find time to add the content
