### ISSUE TITLE
Link to ENG-FUNDAMENTALS-CHECKLIST.md is missing in README

### ISSUE THREAD

**Issue by akirakakar** [microsoft/code-with-engineering-playbook#460]
The tech-leads-checklist.md was accidentally removed in #453 - it needs to be added back as engineering-fundamentals-checklist.md and linked from the [main readme](https://github.com/microsoft/code-with-engineering-playbook#quicklinks)

**Comment by TessFerrandez** [comment]
Funny, was just about to add an issue to add the markdown link checker

**Comment by akirakakar** [comment]
Regarding broken link for ENG-FUNDAMENTALS-CHECKLIST.md, I am thinking of removing the related sentence since I could not find the file. Later, if we want to add this file, we can add back the content related to eng-fundementals-checklist.

What do you think?

**Comment by omusavi** [comment]
I just noticed this and commented in the PR that caused it #453. I think it was moved and not re-added. @cteicher-m for reference

**Comment by TessFerrandez** [comment]
As this issue is really 3 issues in one - let's split them out. I will change this one to only be about adding the content back and changing the link.
