### ISSUE TITLE
Duplicate content on pull request templates

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/code-with-engineering-playbook#469]
The [Pull Request Template](https://github.com/microsoft/code-with-engineering-playbook/blob/master/code-reviews/pull-request-template.md) in Code Reviews and the [Pull Request section](https://github.com/microsoft/code-with-engineering-playbook/tree/master/source-control/pull-request-templates) under Source Control should be consolidated, or linked

**Comment by katyamust** [comment]
I reviewed the content and suggest to drop the content inside code reviews section. Content in source control section is decent and very well written. I believe though pull request template topic belongs to  Code review section and then suggest to move it there.  Please give your view: @TessFerrandez @magencio @tompaana

**Comment by tompaana** [comment]
I agree with @katyamust  

Although I'd perhaps associate PRs more with code reviews, the existing content under source control topic is better so it's easier just to remove the PR template under code reviews and update links.
