### ISSUE TITLE
Pull Requests - Size Guidance - List should be re-worded

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/code-with-engineering-playbook#474]
https://github.com/microsoft/code-with-engineering-playbook/blob/master/code-reviews/pull-requests.md

Besides the size, remember that every PR should:

- Be consistent,
- not break the build, and
- include related tests as part of the PR.

It looks a bit weird, as if it is a sentence that is just split in 3

**Comment by katyamust** [comment]
@TessFerrandez I just saw this issue and actually addressed this in my PR about commit message: https://github.com/microsoft/code-with-engineering-playbook/pull/525
Could you please take a look! I am very keen to hear you view and suggestions. Could we attach this issue to that PR?

**Comment by tompaana** [comment]
Fixed by #525
