### ISSUE TITLE
Duplicate Content on Commit Message Standardization

### ISSUE THREAD

**Issue by TessFerrandez** [microsoft/code-with-engineering-playbook#475]
https://github.com/microsoft/code-with-engineering-playbook/blob/master/code-reviews/pull-requests.md
has content on commit message standardization - so does https://github.com/microsoft/code-with-engineering-playbook/tree/master/source-control - we should consolidate them to one

**Comment by katyamust** [comment]
Commit Message  belongs to Source code section and suggest to move it there from code reviews with relevant content. @TessFerrandez  let me know what you think - I can create appropriate PR suggestion then.
