### ISSUE TITLE
Broken links in security guidelines for OWASP

### ISSUE THREAD

**Issue by lakshaykaushik** [microsoft/code-with-engineering-playbook#499]
Below links were broken:
1.  Clicking on Web Application Security Quick Reference returns 404.
2. Clicking on Security Mindset/Creating a Security Program Quick Start returns 404.

**Comment by lakshaykaushik** [comment]
This issue will be closed by https://github.com/microsoft/code-with-engineering-playbook/pull/497

**Comment by TessFerrandez** [comment]
Closed by PR
