### ISSUE TITLE
Make GitHub Pages link more visible

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/code-with-engineering-playbook#518]
Lets make the github pages link more visible: https://microsoft.github.io/code-with-engineering-playbook/

There should be a website field in the repo's "about" section 

![Screen Shot 2021-02-11 at 2 24 18 PM](https://user-images.githubusercontent.com/16144158/107687957-1d17bb00-6c75-11eb-8a34-c1f1edfd191b.png)

Could also be valuable to add it to the README file.

**Comment by fnocera** [comment]
@Ethan-Arrowood addressed! :) 
<img width="321" alt="Screen Shot 2021-02-11 at 2 35 19 PM" src="https://user-images.githubusercontent.com/10625466/107689114-70d6d400-6c76-11eb-8597-2046b9508245.png">
