### ISSUE TITLE
Engineering Checklist Definition: Security definition "Separation of Concerns"

### ISSUE THREAD

**Issue by dariuszparys** [microsoft/code-with-engineering-playbook#537]
As this came up in our team discussion, what exactly is meant with **Separation of Concerns**. Is the architectural pattern meant by this, if so why is it solely listed in the security section?

**Comment by TessFerrandez** [comment]
@anthturner can you comment here

**Comment by TessFerrandez** [comment]
Removing this as part of #553 but this issue can be repurposed to adding this back when we sort out what it means
