### ISSUE TITLE
content on grooming

### ISSUE THREAD

**Issue by charleszipp** [microsoft/code-with-engineering-playbook#55]
This is for the new proposed outline in #53 

Using the suggested template below as a guide, describe the concept of grooming and what role it plays in scrum. This should include (but not limited to)

- Inputs: What are requirements to have this meeting (i.e. stories ready for estimation)
- Participants required
- Outputs: What decisions or actions are needed to conclude the meeting?

May also elaborate on
- Criteria for knowing when story is ready to estimate (i.e. implementation is understood, testable, clear understanding of what success looks like)
- Estimation 
    - Voting without influencing
    - Resolving estimation conflicts (two people are sizing differently)

### Goals
What are the intended outcomes of the ceremonies?

### Participation
What members of the team should participate?

### Impact
What positive impact has been observed as a result of this practice?

### Measures
How might one measure the impact of this ceremony positive or negative?

### Facilitation Guidance
How might one go about running the ceremony? Is there a general pattern that the ceremony should follow?

**Comment by fnocera** [comment]
Please add content on grooming here https://github.com/microsoft/code-with-engineering-playbook/tree/master/backlog-management/grooming

**Comment by TessFerrandez** [comment]
looking at the content on backlog refinement - it looks to me like this issue might be resolved - I added a separate issue to remove the todo and replace it with a ticket instead - can you check the content and see if this issue is resolved @bsherwin
