### ISSUE TITLE
content for planning

### ISSUE THREAD

**Issue by charleszipp** [microsoft/code-with-engineering-playbook#56]
This is for the new proposed outline in #53 

Using the suggested template below as a guide, describe the concept of planning in scrum. This should include (but not limited to)

- Inputs: What are the pre-reqs for planning (i.e. estimated & prioritized stories)
- Participants
- Outputs: What decisions or actions are needed to conclude the meeting?
- Determining team capacity
- Tasking stories in sprint backlog
     - Size of tasks
     - Hour estimates
     - Updating todo hours
- Dividing work into WIP (work-in-progress) or Workstreams

### Goals
What are the intended outcomes of the ceremonies?

### Participation
What members of the team should participate?

### Impact
What positive impact has been observed as a result of this practice?

### Measures
How might one measure the impact of this ceremony positive or negative?

### Facilitation Guidance
How might one go about running the ceremony? Is there a general pattern that the ceremony should follow?

**Comment by fnocera** [comment]
Please add content on planning here https://github.com/microsoft/code-with-engineering-playbook/tree/master/sprint-planning

**Comment by meulta** [comment]
I am happy to take on a first pass at this, unless someone if already working on it?
