### ISSUE TITLE
Identify observability frameworks/tools and add links to starter guides

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/code-with-engineering-playbook#562]
**Issue**:
Team invested time to spike and understand if a observability framework (Open Telemetry) will fit their needs. When a framework is not ready for prime time, multiple teams go down the same investigation path. 

Notes:
Identify observability frameworks/tools and add links to starter guides.

For example - Open Telemetry - starter guide (I thnk we already have this one on the PB)

**Comment by TessFerrandez** [comment]
@narmathabala - this issue has been stale for a while, is it still relevant with an active plan or should it be closed

**Comment by NarmathaBala** [comment]
Content added
