### ISSUE TITLE
Guidance on one vs multiple instance of telemetry/partitioning usage

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/code-with-engineering-playbook#563]
This is a repeat question in multiple channels. The content will provide guidance on choosing if the telemetry instance should be single/multi instance. Pros and cons of each approach

**Comment by TessFerrandez** [comment]
@narmathabala - this issue has been stale for a while, is it still relevant with an active plan or should it be closed

**Comment by NarmathaBala** [comment]
Closing for now, will be added as needed
