### ISSUE TITLE
content  on scrum-of-scrums

### ISSUE THREAD

**Issue by charleszipp** [microsoft/code-with-engineering-playbook#57]
This is for the new proposed outline in #53 

Using the suggested template below as a guide, describe the concept of scrum of scrums . This should include (but not limited to)

- Inputs: What are team members expected to do before scrum of scrums (i.e. determine dependent work or work that may affect other teams)
- Participants
- Outputs: What decisions or actions are needed to conclude the meeting?

### Goals
What are the intended outcomes of the ceremonies?

### Participation
What members of the team should participate?

### Impact
What positive impact has been observed as a result of this practice?

### Measures
How might one measure the impact of this ceremony positive or negative?

### Facilitation Guidance
How might one go about running the ceremony? Is there a general pattern that the ceremony should follow?

**Comment by fnocera** [comment]
Please contribute content on scrum-of-scrums here https://github.com/microsoft/code-with-engineering-playbook/tree/master/scrum-of-scrums
