### ISSUE TITLE
content on estimation

### ISSUE THREAD

**Issue by charleszipp** [microsoft/code-with-engineering-playbook#58]
This is for the new proposed outline in #53 

This content should guide a new team in how to establish how they will be doing estimation. 
- Agreed scale (i.e. fibonacci)
- Conversion ration of points in scale back to unit of time (i.e. 1 point  = 1 day for 1 contributor)
- Establishing baseline stories (i.e. pick story that represents a 5 and one that represents 2 if using fibonacci)

**Comment by fnocera** [comment]
Content on Estimation best practices to be added here: https://github.com/microsoft/code-with-engineering-playbook/tree/master/sprint-planning/estimation
