### ISSUE TITLE
Question: do we want extremely basic 'getting started' guidance?

### ISSUE THREAD

**Issue by zoekdestep** [microsoft/code-with-engineering-playbook#587]
Hi team!

The last project we worked on, we had a few POs working with us, who had limited technical knowledge but who still needed to add .md files to the repository. We wrote a very basic 'getting started' guide for them, consisting of the following items:

- Glossary (e.g., what is a PR, what is a merge conflict, what is a CI pipeline, etc)
- How to install the necessary tools (VSCode, Git)
- How to clone a repo
- How to create a first branch in ADO
- How to create .md files and save them, with right linting/spell checking
- How to commit and push
- How to create a PR, and how to comment on it and complete it

Do you think this would be useful to include in the playbook? If yes, any suggestions on where to store this? 

Thank you!

(also tagging @TessFerrandez and @katyamust as I'm sure you have an idea about this!)

**Comment by TessFerrandez** [comment]
I'm a little torn - I feel like that is covered quite well in the referenced post [Hello World · GitHub Guides](https://guides.github.com/activities/hello-world/) and also in the playbook itself [code-with-engineering-playbook/readme.md at master · microsoft/code-with-engineering-playbook (github.com)](https://github.com/microsoft/code-with-engineering-playbook/blob/master/source-control/git-guidance/readme.md) 

What do we feel is missing?

**Comment by TessFerrandez** [comment]
Closing as inactive - feel free to reopen if you feel this was done in error
