### ISSUE TITLE
content for definition-of-ready

### ISSUE THREAD

**Issue by charleszipp** [microsoft/code-with-engineering-playbook#59]
This is for the new proposed outline in #53 

This content should define the criteria a team should use to determine if a story is ready to pull into a sprint. Example is, team understands the implementation, how to prove work meets acceptance, estimated, etc.

**Comment by fnocera** [comment]
To be added here https://github.com/microsoft/code-with-engineering-playbook/tree/master/team-agreements/definition-of-ready
