### ISSUE TITLE
Add "Communication and documentation" best practices to Documentation section

### ISSUE THREAD

**Issue by magencio** [microsoft/code-with-engineering-playbook#597]
After the new Documentation section is created (#533), add a new "Communication and documentation" document under "Best practices".

Ideas for content:

- Communication channels.
  - In-person vs. phone vs. email vs. Teams/Slack vs. Discussion section in Wiki/tasks vs. …
- Recording decisions/changes.
- Communicating decisions/changes.
  - E.g., Channels in Teams: General, Breaking Changes, Meetings, PRs, Workstreams

**Comment by TessFerrandez** [comment]
@magencio - is this issue still relevant, and active or ok to close?
