### ISSUE TITLE
Add "Making documentation discoverable" best practices to Documentation section

### ISSUE THREAD

**Issue by magencio** [microsoft/code-with-engineering-playbook#598]
After the new Documentation section is created (#533), add a new "Making documentation discoverable" document under "Best practices".

Idea to consider: Providing sample documentation structure of a project/repository. Also with respect to different type of documentation: team agreements, on-boarding guides, CI/CD, technical documentation of the components etc. Technical docs far away from the implementation have higher risk of not being noticed/**updated**.

The work done in #646 would also help with documentation discoverability. 

This article could also be helpful: [Monorepo For Beginners](https://mtirion.medium.com/monorepo-for-beginners-45d5059ab40e)

**Comment by TessFerrandez** [comment]
@magencio - is this issue still relevant, and active or ok to close?
