### ISSUE TITLE
Add "Security" documentation guidance to Documentation section

### ISSUE THREAD

**Issue by magencio** [microsoft/code-with-engineering-playbook#602]
After the new Documentation section is created (#533), add a new "Security" document under "What documentation should exist" (in documentation/guidance folder).

Ideas for content:

- Artifacts.
  - Threat models.
  - Security requirements.
  - Reports.
  - Lessons learned.

**Comment by TessFerrandez** [comment]
@magencio - is this issue still relevant, and active or ok to close?
