### ISSUE TITLE
Create guidelines for inclusive Code Review

### ISSUE THREAD

**Issue by madossan01** [microsoft/code-with-engineering-playbook#606]
**Is your feature request related to a problem? Please describe.**
When reviewing code or documentation it is important to consider to use inclusive language. 
The review and the author perspectives must be considered.

**Describe the solution you'd like**
The playbook could provide guidelines for inclusive Code Review: 
For this Guideline, please consider some research topics as below:
	1. Why care about inclusivity in code reviews
	2. Types of non-inclusive code review behavior
	3. Inclusive code reviews behaviors​
		a. Considerations for the development Team
		b. The reviewer​ and the code author perspectives
	4. Tools that can help with inclusive code reviews. Some suggestions below:
	• https://github.com/tdurieux/anonymous_github​
	• https://github.com/zombie/blind-reviews/​
	• https://www.gitmask.com/

**Describe alternatives you've considered**
Not applicable

**Additional context**
This feature was proposed based on one internal crew research called "Inclusive Code Reviews 01".

**Comment by TessFerrandez** [comment]
Closing as it was moved to done
