### ISSUE TITLE
Consider Adding: "Prefer .drawio.png image formats for diagrams"

### ISSUE THREAD

**Issue by NickDrouin** [microsoft/code-with-engineering-playbook#619]
Consider standardizing on using *.drawio.png as the preferred format for diagrams to embed .md files.
 
With both a web ux (diagrams.net) and a plugin for VSCode (hediet.vscode-drawio) it is easy to author and edit png diagrams.
 
Details:
The drawio format uses the metadata layer within the png file-format to hide svg vector graphics representation, then renders the .png when saving.  This clever use of both the meta layer and image layer allows anyone to further edit the png file.  It also renders like a normal PNG in browsers and other viewers, making it easy to transfer and embed.
 
You can use it like you would Visio or LucidChart (also great, but all sorts of licensing and files kept remotely, so data-protection concerns).  It has a collection of Azure/Office/Microsoft icons, as well as other well-known tech, so not only can you do swimlanes and flow diagrams, but architecture as well.

**Comment by TessFerrandez** [comment]
Close per PR
