### ISSUE TITLE
WIP: Weekly Sprint Developer Loop

### ISSUE THREAD

**Issue by ianphil** [microsoft/code-with-engineering-playbook#62]
Monday Sprint Planning

Wednesday EOD finish stories

Thursday Morning PR

Thursday EOD PR review / fix

Friday Create demo video

Friday EOD Retro

**Comment by charleszipp** [comment]
Heres my sample outline

Day 1 
-	Planning
-	Tasking
-	Test Cases Agreed Started
-	Implementation Plan Agreed and Started

Day 2
-	Test cases complete
-	At or near code completion

Day 3
-	PR’s submitted
-	Code reviewed
-	Code tested pre merge
Day 4
-	PR’s merged
-	Stories tested from master
-	Deployed to demo environment
Day 5
-	Sprint Demo
-	Retro
-	Grooming/Estimation for next sprint

**Comment by nmiodice** [comment]
Question -- this may be context I missed on Friday so apologies if this has been covered. How do design stories that may not have an implementation fit into the proposed workflow? Also how do we handle tasks that require > 1 day (keeping in mind meetings, variable schedules etc...) to implement?
