### ISSUE TITLE
Guidance on using OSS - Checking for Licenses and Copyrights

### ISSUE THREAD

**Issue by janine-zhu** [microsoft/code-with-engineering-playbook#623]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TessFerrandez** [comment]
Hi @janine-zhu and @jskulavik -- this issue has been stale for a while... are you working on a PR for this?

**Comment by jskulavik** [comment]
@janine-zhu, can we close this out?
