### ISSUE TITLE
Bash best practices

### ISSUE THREAD

**Issue by lawrencegripper** [microsoft/code-with-engineering-playbook#65]
It's pretty common that we use lots of `bash` scripts to wire things together. 

Is it worth including a section on how to lint/check `bash`?

Currently use the following to run `shellcheck` as part of an `azuredevops` pipeline. 

```
- bash: |
    echo "This checks for formatting and common bash errors. See wiki for error details and ignore options: https://github.com/koalaman/shellcheck/wiki/SC1000"
    export scversion="stable"
    wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
    sudo mv "shellcheck-${scversion}/shellcheck" /usr/bin/
    rm -r "shellcheck-${scversion}"
    shellcheck ./scripts/*.sh
  displayName: "Validate Scripts: Shellcheck"

```

**Comment by jjcollinge** [comment]
including when **not** to use bash and use something like Python... In the spirit of openness Google's style guide is a good reference: https://google.github.io/styleguide/shell.xml

**Comment by lawrencegripper** [comment]
100% agree, `bash` is the common choice but it doesn't mean it's the right choice. We focused on using python lots with OpenCGA as it gave better readability and testability [examples](https://github.com/opencb/opencga/tree/develop/opencga-app/app/scripts/azure/arm/scripts).

**Comment by fnocera** [comment]
We have added a bash code review section [here](https://github.com/microsoft/code-with-engineering-playbook/blob/master/pull-requests/code-reviews/recipes/Bash.md) please let me know if this addresses needs or if we require additional content.

**Comment by lawrencegripper** [comment]
Yes LTGM - I've added the ready to go snippet for including in ADO too: https://github.com/microsoft/code-with-engineering-playbook/pull/76
