### ISSUE TITLE
[BUG] Invalid URI for Shellcheck

### ISSUE THREAD

**Issue by mcollier** [microsoft/code-with-engineering-playbook#651]
**Describe the bug**
The bash script suggested for the Azure DevOps pipeline validation is invalid.  The inline script uses a URL for shellcheck which is no longer valid. Per the guidance at https://github.com/koalaman/shellcheck/issues/1871, releases should use the downloads from the Github releases, not https://storage.googleapis.com/shellcheck.

**To Reproduce**
1. Execute the script defined at https://github.com/microsoft/code-with-engineering-playbook/blob/main/docs/code-reviews/recipes/bash.md#build-validation
2. Run `shellcheck` against a .sh file.
3. Observe the following output message:
```
You are downloading ShellCheck from an outdated URL!

Please update to the new URL:
https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz

For more information, see:
https://github.com/koalaman/shellcheck/issues/1871

PS: Sorry for breaking your build :(
```

**Comment by tompaana** [comment]
Fixed by #725
