### ISSUE TITLE
[BUG] Recipe for Detect Secrets in Azure DevOps is outdated

### ISSUE THREAD

**Issue by mcollier** [microsoft/code-with-engineering-playbook#655]
**Describe the bug**
The recipe at https://github.com/microsoft/code-with-engineering-playbook/blob/main/docs/continuous-integration/dev-sec-ops/secret-management/recipes/detect-secrets-ado.md seems to be outdated.  

I could not get the provide pipeline file to successfully execute.  When trying to run the detect-secrets script, I received errors in Azure DevOps related to invalid options for `--use-all-plugins` and `--custom-plugins`.  It seems those options are no longer needed for the newest (1.1.0) version of detect-secrets.

Additionally, the Azure Storage Account Key detection seems to be included in the default built-in plugins for detect-secrets, starting with version 1.0.0 ([changelog](https://github.com/Yelp/detect-secrets/blob/master/CHANGELOG.md#v100)).  Thus, the custom plugin referenced in the recipe would not be needed.

Moreover, when using Python 3.9, I couldn't get detect-secrets to detect any secrets.  I found an issue at https://github.com/Yelp/detect-secrets/issues/452 which suggested reverting to detect-secrets version 1.0.3.  That resolved the error, but the tool still failed to detect secrets.  It would seem additional guidance may be needed in the recipe to help a user determine the correct version of Python and detect-secrets to use.

Moreover, the usage guidance differs from the non-Azure DevOps detect-secrets usage at https://github.com/microsoft/code-with-engineering-playbook/blob/main/docs/continuous-integration/dev-sec-ops/secret-management/recipes/detect-secrets.md.  This makes trying to figure out how to use detect-secrets in a project confusing.  I would assume that the basic commands for detect-secrets usage should be similar, regardless of using Azure DevOps or running locally.

There isn't just one bug with the recipe for detect-secrets, but several obstacles that made it difficult to use.  I ended up going another route.

**Comment by DariuszPorowski** [comment]
Hi @mcollier I updated the recipe https://github.com/microsoft/code-with-engineering-playbook/pull/716
I addressed all your comments in this PR besides the last one. Detect-Secrets has different usage scenarios with or without baseline.
ADO example uses the most straightforward case without baseline diff. It means Detect-Secrets always scan all files and give results about all detected secrets.
I think recipes with baseline should be updated and explained well include use case scenarios.
