### ISSUE TITLE
Creating API contract with Design-first or Code-first Approach

### ISSUE THREAD

**Issue by cpeeyush** [microsoft/code-with-engineering-playbook#660]
**Is your feature request related to a problem? Please describe.**
As now days development teams widely use API description formats like Swagger (OpenAPI) to describe an API contracts, which brings a question whether a dev team should design an API contract first or write code first and generate api contract out of it. 

**Describe the solution you'd like**
Add a section in playbook to describe both API development approaches.

**Describe alternatives you've considered**
Add links of some existing reliable source blog posts within a section in playbook.

**Comment by fnocera** [comment]
@cpeeyush, thanks for your patience while we discussed guidance on where this contribution should go. We now have a new structure brought in as part of PR #678 where we will have a design folder (design fundamental) and within this we will have "design reviews" and "design patterns". 

You will also see that there will be some updates to #642 which will be adding the REST API Guidance to the design patterns section in the next few days. Your contributions on laying out aspects to consider and a pros/cons comparison of both Design-first and Code-first Approaches would be very welcome and would fit nicely as a section within the REST API Guidance that @bderusha is working on. 

Happy to sync to provide more guidance and will reach out by chat as well!
