### ISSUE TITLE
Recipe for Doc-String in python

### ISSUE THREAD

**Issue by akirakakar** [microsoft/code-with-engineering-playbook#668]
**Is your feature request related to a problem? Please describe.**
I'm always confused what doc-string style I should use and why.

**Describe the solution you'd like**
List up options for doc-string style with pros and cons.

**Describe alternatives you've considered**
Just pick the best one we think we should recommend.

**Comment by TessFerrandez** [comment]
@magencio,  @akirakakar - is this issue still relevant, and active or ok to close?

**Comment by magencio** [comment]
Sorry, we missed this issue. As it wasn't assigned to the Engineering Playbook Backlog project it didn't show up in our backlog. So, I'm not sure if this is still relevant. @akirakakar, may you confirm? Thank you and sorry for that.

**Comment by TessFerrandez** [comment]
Our general guidelines for code style for python is to use Pep8 and this is already documented in the playbook.
