### ISSUE TITLE
Revamp contributing.md to make triage contacts and content guidelines clearer

### ISSUE THREAD

**Issue by fnocera** [microsoft/code-with-engineering-playbook#675]
**Is your feature request related to a problem? Please describe.**
Contributing to the playbook can be confusing as the contributing.md file does not really mention what to do beyond opening an issue. Ideally we would have some guidance on _what to contribute_ as well as _who to engage_ when creating an issue (ie: triage contacts). This would allow us to get back to folks more quickly and give any feedback before content is created and PRs are opened. 

**Describe the solution you'd like**
Contributing.md file is edited to: 
- include guidance on the playbooks focus being mainly around the fundamentals, with some specific technical use cases where relevant as well as focussing on sharing links to useful resources vs replicating content. 
- include a list of triage contacts by engineering fundamental area for folks to add to their issue as part of the triage process

**Describe alternatives you've considered**
Having the contributing guidance in our CSE wiki does not cover all cases and can be difficult to find. It would be better to have guidance both in the wiki and in the playbook itself.

**Comment by fnocera** [comment]
Interested in your input on this in case I missed anything from our conversation @charleszipp @TessFerrandez @NarmathaBala

**Comment by charleszipp** [comment]
This is great @fnocera. This makes me think we should maybe we should agree on the triage process first so we can set expectations with potential contributors? For example, should we set a reoccurring time for maintainers to meet and triage new issues? I have some ideas about this we can discuss at the next sync.

**Comment by zmmille2** [comment]
I'd suggest we also update [the pull request template](https://github.com/microsoft/code-with-engineering-playbook/blob/main/.github/pull_request_template.md) so CONTRIBUTING.md is referenced.

**Comment by NarmathaBala** [comment]
This is great, @fnocera. Here are a couple of things that come to mind
1. To add more clarity and direction to first timers, we could also add a welcome bot that will help with general sense of "direction" before a new PR is created.
https://github.com/apps/welcome
2. Auto assign leads on PR reviews based on Label tags (This will take the manual tagging out for repeat contributors)
