### ISSUE TITLE
Add content on Engineering Feasibility Spikes to de-risk engagements when using new technologies 

### ISSUE THREAD

**Issue by fnocera** [microsoft/code-with-engineering-playbook#683]
**Is your feature request related to a problem? Please describe.**
Currently the Playbook contains an entry around Technical Spikes but this content does not include details on how spikes can be used to identify and mitigate risk. 

**Describe the solution you'd like**
We propose adding a recipe around Technical Feasibility Spikes/Engineering Feasibility Spikes to help identify technical areas that require deeper investigation, share learnings and prioritize future spikes.

**Describe alternatives you've considered**
N/A (This is a new approach that has come out of recent engagements and has worked well for our crew)

**Additional context**
This approach can be combined with a premortem and is very effective in the Envisioning/ADS stage of engagements.

**Comment by fnocera** [comment]
@zmmille2 Would love to get your thoughts on the above!

**Comment by zmmille2** [comment]
Looks wonderful, I'm excited to see what recommendations came out from the engagement. It seems like this might have a lot in common with [the current recommendations around decision logs](https://github.com/microsoft/code-with-engineering-playbook/tree/main/docs/design-reviews/decision-log): If they're related, maybe we can add in some cross references?

Either way, thank you for contributing back to the playbook.

**Comment by fnocera** [comment]
@zmmille2 I love the suggestion of linking it to decision logs! It seems like the conclusion/outcome of the Engineering Feasibility Spikes could very much be to refactor the content or create content with a slightly different focus, perhaps once the uncertainty is removed, and to create a decision log!

**Comment by zmmille2** [comment]
Also worth mentioning that [the current section on technical spikes](https://github.com/microsoft/code-with-engineering-playbook/blob/main/docs/design-reviews/recipes/technical-spike.md) does mention mitigating risks in passing:

>A spike in a sprint can be used in a number of ways:
>...
>Spike tests can also be used to mitigate future risk, and may uncover additional issues that have escaped notice.

Any new content would do well to highlight the differences between technical spikes and Engineering Feasibility Spikes.
