### ISSUE TITLE
Suggestion: Repository should match its own source control best practice

### ISSUE THREAD

**Issue by johnddonnelly** [microsoft/code-with-engineering-playbook#70]
[Source control page](https://github.com/microsoft/code-with-engineering-playbook/blob/master/Engineering/SourceControl.md) has requirements that don't seem to have been met yet for this repo

- agree on their branch, release and merge strategy
- define their approach to commit history (linear or non-linear)
- agree on how to name branches (e.g. user/your_alias/feature_name)

Can we agree the answers for these questions, for this repo, and add to the contributing page?

**Comment by fnocera** [comment]
@johnddonnelly please could you review the new restructured content https://github.com/microsoft/code-with-engineering-playbook/tree/master/source-control and let me know how we can improve/address your concerns. Thanks!
