### ISSUE TITLE
Add Open Telemetry design patterns & recipes

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/code-with-engineering-playbook#735]
**Is your feature request related to a problem? Please describe.**
CSE Playbook does not have content on design patterns & recipes related to Open Telemetry

**Describe the solution you'd like**
Based on our conversations, please review content in Open Telemetry page https://microsoft.github.io/code-with-engineering-playbook/observability/tools/OpenTelemetry/ and recommended design patterns.

Also add pointers to Recipes section in https://microsoft.github.io/code-with-engineering-playbook/observability/recipes-observability/

**Comment by eedorenko** [comment]
Hi @iamnicoj, 
I am currently working on [distributed tracing in IoT](https://dev.azure.com/csedevops/IoTStarter/_wiki/wikis/IoTStarter.wiki/56/Distributed-Tracing) and digging deeply into OpenTelemetry. It would be nice to collaborate on this item.

**Comment by iamnicoj** [comment]
Sure @eedorenko, I'll ping you next week to have a small talk about this. Thanks

**Comment by zmmille2** [comment]
Closing as part of #792.
