### ISSUE TITLE
Add evolved trade study and sprint spike templates

### ISSUE THREAD

**Issue by abpham** [microsoft/code-with-engineering-playbook#740]
**Is your feature request related to a problem? Please describe.**
Spike and design doc templates were generated and used throughout a recent customer engagement. The playbook could benefit from these templates and help accelerate the design documentation process in future projects.

**Describe the solution you'd like**
We would like to contribute Markdown templates for spikes and designs to the design section of the Playbook.

**Describe alternatives you've considered**
N/A

**Additional context**
Some templates are iterations on other work currently found in the Playbook (e.g., the design template is a modified version of the template found in ./docs/design/design-reviews/trade-studies).

**Comment by charleszipp** [comment]
To add some more context... in our current engagement, we established a few templates for design/spike related activities. As @abpham mentioned, one is an evolution of the current trade study template. The other is a template we used for spike activities where we had one or a few specific questions we needed to research and answer. This issue will be linked to a PR that @abpham will be opening soon with these contributions. We are planning to add them as adjacent and alternative templates as to preserve the originals.
