### ISSUE TITLE
Reorg recipes for design documentation

### ISSUE THREAD

**Issue by meghapatilcode** [microsoft/code-with-engineering-playbook#754]
**Is your feature request related to a problem? Please describe.**
In our recent engagement, we were searching the playbook for a template to use for design documentation. We tried the following pages and couldn’t find one in here:
1. [Design - Code With Engineering Playbook (microsoft.github.io)](https://microsoft.github.io/code-with-engineering-playbook/design/)
2. Design Documentation section under [Design Reviews - Code With Engineering Playbook (microsoft.github.io)](https://microsoft.github.io/code-with-engineering-playbook/design/design-reviews/)

On digging deeper, we realized the templates for design documentation are under **Recipes** section, but hyperlinked from the [Design Reviews](https://microsoft.github.io/code-with-engineering-playbook/design/design-reviews/) page under the section **Design Review Templates**.

**Describe the solution you'd like**
We think the **Design Review Templates** section would be a better fit under the [Design](https://microsoft.github.io/code-with-engineering-playbook/design/) page as a **Design Documentation Templates** section than under the [Design Review](https://microsoft.github.io/code-with-engineering-playbook/design/design-reviews/) page, since anyone looking for guidance on items to consider while designing and documentation would intuitively look under the Design section.

**Describe alternatives you've considered**
An alternative solution would be to hyperlink the Recipes from **Design Documentation** section in the [Design Reviews](https://microsoft.github.io/code-with-engineering-playbook/design/design-reviews/) page, but that would be mean duplicating the links from the **Design Review Templates** section above.

**Comment by zmmille2** [comment]
As per our sync, we will pull the Design Review Templates up to the Design section, and rename the section "Design Templates", and update the Design Review Recipes section to still read well.
