### ISSUE TITLE
Add Postman + Newman as a common recipe for testing CRUD APIs

### ISSUE THREAD

**Issue by alkofahi** [microsoft/code-with-engineering-playbook#755]
**Is your feature request related to a problem? Please describe.**
Implementing E2E or Integration tests for a service with CRUD APIs.

**Describe the solution you'd like**
A quick and neat way to implement such test automation is by using [Postman](https://www.postman.com/) to implement the tests and then incorporate them into your pipelines using [Newman](https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/#:~:text=Newman%20is%20a%20command%2Dline,directly%20from%20the%20command%20line.&text=Newman%20maintains%20feature%20parity%20with,the%20collection%20runner%20in%20Postman.)

This can be documented in the automated testing section as a common pattern for future reference.

**Comment by TessFerrandez** [comment]
@alkofahi - is this issue still relevant, and active or ok to close?
