### ISSUE TITLE
Automated testing workshop

### ISSUE THREAD

**Issue by alkofahi** [microsoft/code-with-engineering-playbook#756]
**Is your feature request related to a problem? Please describe.**
The dev crew's testing needs vary depending on their engagements. But the challenge here is to be aware of the test types applicable to one’s engagement and how to upskill on those test types to deliver the right tests for the engagement.

**Describe the solution you'd like**
The group discussed creating a workshop to tackle this challenge. This task tracks the workshop proposal as a reference for other tasks.

One pager [Automated Testing EF workshop proposal.docx](https://github.com/microsoft/code-with-engineering-playbook/files/7542770/Automated.Testing.EF.workshop.proposal.docx)

**Comment by TessFerrandez** [comment]
@alkofahi - this seems to be tracking work that is not related to the playbook - would it be possible to track this work elsewhere?
I will close the issue in the playbook repo, but just letting you know so you have a chance to add it to another issue system
