### ISSUE TITLE
Merge existing Accessibility work from HX Team to UI/UX document

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/code-with-engineering-playbook#768]
Excitingly, @JankaKoen will be helping out the UI/UX group from a Human Experience perspective. She will be merging some existing work from her end into the UI/UX Accessibility page. This issue exists to track this work as it will not be completed until 2022 due to overlapping vacation times ❄️

**Comment by squassina** [comment]
@shanedjones, this is somewhat related to what we are doing, right?

**Comment by shiranr** [comment]
@JankaKoen @Ethan-Arrowood I am cleaning up stale issues, is this still relevant for you? are you working on these issues?

**Comment by JankaKoen** [comment]
Hi! No, I am not working on this, nor am I planning on that at the moment.

**Comment by TessFerrandez** [comment]
This was handled in a separate PR
