### ISSUE TITLE
[Code reviews] Unify tools page

### ISSUE THREAD

**Issue by tompaana** [microsoft/code-with-engineering-playbook#782]
The existing pages "Configuring branch policies" and "Customize ADO" are stubs and too short to be justified to exist as stand-alone pages. These should be combined into the existing "Code Review Tools" page with the relevant related information.

**Comment by ikivanc** [comment]
@shiranr, @tompaana is this issue resolved with PR #803?

**Comment by tompaana** [comment]
@ikivanc Yes, closing the issue now.
