### ISSUE TITLE
Updates to envisioning documentation

### ISSUE THREAD

**Issue by niwilso** [microsoft/code-with-engineering-playbook#795]
**Is your feature request related to a problem? Please describe.**
The current [Envisioning and Problem Formulation page](https://github.com/microsoft/code-with-engineering-playbook/blob/main/docs/machine-learning/ml-problem-formulation-envisioning.md) does not inform the reader that *who* we work with are not necessarily the end-users of the solution we are striving to build. In addition, we believe there is room to include some more guidance on the envisioning process.

**Describe the solution you'd like**
I will be creating a Pull Request with requested changes to the [Envisioning and Problem Formulation page](https://github.com/microsoft/code-with-engineering-playbook/blob/main/docs/machine-learning/ml-problem-formulation-envisioning.md). The PR will also include a template exit-document for the envisioning process and include a list of sample onboarding questions to provide next steps for the reader.

**Describe alternatives you've considered**
We (mainly Zikra Toure) have reached out to contributors of the code-with-engineering-playbook to ensure they were aware.

**Additional context**
The proposed edits were the result of an internal design review meeting discussion.

**Comment by zmmille2** [comment]
Closed as part of #796
