### ISSUE TITLE
[BUG] remove unnecessary/old resources folder

### ISSUE THREAD

**Issue by omri374** [microsoft/code-with-engineering-playbook#797]
The playbook contains a [resources](https://github.com/microsoft/code-with-engineering-playbook/tree/main/docs/resources) section, containing a few files which aren't relevant (IMHO). 
It currently contains a license file, a contributing file with wrong links (submit a pr to goes to https://github.com/xyz, link to a [very old fork of the repo](https://github.com/cloudbeatsch/code-with-engineering-playbook) etc.) and a readme template.

Should we consider removing it? or update it?
@TessFerrandez @wbreza @fnocera

**Comment by TessFerrandez** [comment]
I will take this on

**Comment by TessFerrandez** [comment]
These files are referenced throghout the repo

**Comment by omri374** [comment]
@TessFerrandez in this case should we consider updating it? This file for example: https://github.com/microsoft/code-with-engineering-playbook/blob/main/docs/resources/templates/CONTRIBUTING.md has irrelevant references to:
1. https://github.com/cloudbeatsch/code-with-engineering-playbook
2. https://github.com/xyz
