### ISSUE TITLE
Update Documentation/Languages page for Mermaid.js info

### ISSUE THREAD

**Issue by matt-manuel** [microsoft/code-with-engineering-playbook#865]
**Is your feature request related to a problem? Please describe.**

Some of the Mermaid links can be updated. E.g. the link to the Mermaid live editor is now just https://mermaid.live 

I think adding a mermaid code snippet and the resulting image as an example may help explain the benefits and use of mermaid for documentation.

**Describe the solution you'd like**

* Update some links to the new URLs, e.g. mermaid.live
* Add a sample mermaid.js code snippet and resulting image as an example

**Describe alternatives you've considered**

* Hmm. Not sure. Leaving things as they are? The links still resolve, for example.

**Additional context**

N/A

**Comment by mtirionMSFT** [comment]
@matt-manuel Good suggestions. Can you please create a PR with suggested info?
