### ISSUE TITLE
[BUG] Secrets detected in CWEP code snippet

### ISSUE THREAD

**Issue by day-jeff** [microsoft/code-with-engineering-playbook#893]
We've imported the CWEP into the SolutionOps playbook, and our secrets detection linter detected a page with secrets embedded in code snippets. While this is not "real code," we should not be using code violates security best practices.

**Describe the bug**
Secrets detected on `line 112` of this page:

- [docs/code-with-engineering-playbook/automated-testing/tech-specific-samples/blobstorage-unit-tests/README.md](https://github.com/microsoft/code-with-engineering-playbook/tree/main/docs/automated-testing/tech-specific-samples/blobstorage-unit-tests)

**Comment by bsherwin** [comment]
This is a default value for Azureit, not a private key. See note directly after that code block.

*Note: value for STORAGE_CONNECTION_STRING is default value for Azurite, it's not a private key

**Comment by sharonfinden** [comment]
I think we can close this. Can I get a 2nd for the motion?

**Comment by bsherwin** [comment]
Is there a tag that we can use to clue the linter that we know the secret is not secret for future scans?

(@sharonfinden...I would second this, but it wasn't assigned to me.)
