### ISSUE TITLE
Duplicate content on markdownlint

### ISSUE THREAD

**Issue by algattik** [microsoft/code-with-engineering-playbook#903]
The following pages have overlapping information. This should be reviewed, or at least cross-referenced.

- https://github.com/microsoft/code-with-engineering-playbook/blob/main/docs/code-reviews/recipes/markdown.md
- https://github.com/microsoft/code-with-engineering-playbook/blob/main/docs/continuous-integration/markdown-linting/README.md

**Comment by TessFerrandez** [comment]
Fixed
