### ISSUE TITLE
Guidance and examples informing around Structural vs Behavior Diagrams

### ISSUE THREAD

**Issue by adrian-gonzalez** [microsoft/code-with-engineering-playbook#952]
**Is your feature request related to a problem? Please describe.**

As a developer, one might struggle to determine what diagrams to include as part of my design proposals or code contributions to a project.

**Describe the solution you'd like**
Guidance that first informs readers of the different types/classes of diagrams, and then for each one provides details, resources, and diagram examples.

**Describe alternatives you've considered**
Considered putting this in each customer engagement's working agreement, but realized that it is better suited as a foundational / engineering playbook. 

**Additional context**
Appropriate designs is essential throughout the entire SDLC and lifecycle of a product. 

Design proposals are made up of a lot of different pieces of information. Whether it is conducting trade studies or whether it is influencing a specific approach, a foundational piece of any design is knowing what type of diagram is best suited to convey information with the right amount of information and at the right time of a solution's lifecycle.

**Comment by TessFerrandez** [comment]
Closed by #953
