### ISSUE TITLE
Recipe: Create Cloud Native Example/Tutorial

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/code-with-engineering-playbook#97]
Create a recipe/example/tutorial for adding telemetry to an application

**Comment by mahomedalid** [comment]
I can take this.

**Comment by TessFerrandez** [comment]
@narmathabala and @mahomedalid - last comment on this was that mahomedalid would take this issue and work on it (on Feb 2020) -- is this still an active task or was this already solved but the task was accidentally left open?

**Comment by NarmathaBala** [comment]
Closing for now, will be added as needed
